### ISSUE TITLE
Code in new sounds

### ISSUE THREAD

**Issue by AjTech1089** [t1stm/ThirtyDollarWebsiteConverter#11]
Recently, there were new sounds added in the thirty-dollar website. I want new sounds to be coded into the converter so that way it can recognize these new sounds added into the thirty-dollar website.

**Comment by t1stm** [comment]
The converter automatically gets all currently available sounds from the TDW website. I've attached a screenshot of the code that handles it.
![image](https://github.com/t1stm/ThirtyDollarWebsiteConverter/assets/88944096/d7b8c219-8a36-4b23-8d33-550c5a954ac6)

**Comment by t1stm** [comment]
If you have used it before the update the converter should automatically download the missing samples.

If I remember correctly that's what happened on my end.

**Comment by t1stm** [comment]
I am sorry for not checking deeper earlier... This was an issue with the sample decoder. Issue #12 tracked this issue and I have now fixed it. A new release is on the way. 

Please note that the user interface will change with this release.

**Comment by t1stm** [comment]
The new release is up. [Here's the link.](https://github.com/t1stm/ThirtyDollarWebsiteConverter/releases/tag/v0.9.2-beta)
