### ISSUE TITLE
The volume of each sound (%XX) gives an error

### ISSUE THREAD

**Issue by RefriZaddo** [t1stm/ThirtyDollarWebsiteConverter#9]
**Describe the bug**

Sounds with a volume setting (\<sound\_id\>@\<pitch\>***%\<volume\>***) make it give an error saying that the pitch (\<sound\_id\>@***\<pitch\>***%\<volume\>) isn't in a correct format

**To Reproduce**
1. Try to convert a TDW song with volume settings for each sound
2. See error

**Expected behavior**

It should have been able to interpret the %\<volume\> as a volume setting and continue

**Error**
Write the debugging error here.

`System.FormatException: The input string '-23%78' was not in a correct format.`

**Comment by t1stm** [comment]
It seems that this is an update to the TDW format. When I created this program there was a seperate event called !volume that controlled the volume of a sample. I'll start implementing a fix today and will probably finish it tomorrow.

This is how the project handled volume.
![image](https://github.com/t1stm/ThirtyDollarWebsiteConverter/assets/88944096/cbd1f33a-4c4b-4683-8c59-f5840415de29)

**Comment by t1stm** [comment]
I'll link a branch that fixes this.

**Comment by t1stm** [comment]
The implementation is finished. I'll add a new release later today.

**Comment by t1stm** [comment]
This update for Windows should resolve the issue. [https://github.com/t1stm/ThirtyDollarWebsiteConverter/releases/tag/v0.9.1-beta](Download)
